---
# argument spec file for kpsinghchouhan.linux_management_roles.step_ca

argument_specs:
  main:
    short_description: Role description.
    options:
      step_ca_my_variable:
        type: str
        description: A simple string argument for demonstration.
        default: "default_value"
